app/index.html
app/js/dataprovider.js
app/js/healthmap.js
app/js/map.js

Split out map-related logic into a separate Map class

---

scripts/data_util.py

Make fetching the countries data quiet

---

index.html
scripts/data_util.py
scripts/deploy.py
scripts/run.py

Fix all references after renames and moves

---

scripts/deploy.py

Re-add some files that are needed for deployment

---

css/styles.scss

A little bit of dimming of the mapbox UI, but restore it for autodrive

---

css/_media-queries.scss
css/styles.scss
index.html
js/healthmap.js

Make the side bar collapsible

---

css/_media-queries.scss
css/_variables.scss
css/styles.scss

Simplify CSS variables and media queries

---

css/styles.scss

Minor CSS polishes

---

js/healthmap.js
js/timeanimation.js

Loop the animation in 'autodrive' mode

---

js/timeanimation.js
scripts/deploy.py

Minor JS compilation fixes

---

js/healthmap.js

Add a short delay before restarting the animation

---

js/diseasemap.js
js/externs_mapbox.js
js/healthmap.js

Add a simple 3D mode. Separate hash processing into a separate function

---

js/externs_d3.js

Get rid of the last two JS compilation warnings

---

country.html
index.html
js/graphing.js
js/healthmap.js
scripts/js_compilation.py

Split out graphing functionality into a separate function.

---

js/diseasemap.js
js/graphing.js
js/healthmap.js

Support graphing cases for several geoids at once on the same graph

---

country.html
css/styles.scss
index.html
js/dataprovider.js
js/diseasemap.js
js/externs_chart.js
js/externs_d3.js
js/graphing.js
js/graphing_test.js
js/healthmap.js
scripts/js_compilation.py
tests/js_test.py

Many enhancements to case graphs

---

js/country.js
js/dataprovider.js
js/diseasemap.js
js/externs_mapbox.js
js/healthmap.js

Add a link to the relevant country dashboard in popups

---

js/diseasemap.js

Close popups on click

---

js/diseasemap.js

Show popups on click rather than hover

---

css/_media-queries.scss
css/styles.scss
index.html
js/country.js
js/dataprovider.js
js/healthmap.js
scripts/data_util.py

Add a "per capita" feature to the country list

---

completeness/index.html
js/dataprovider.js
js/healthmap.js

Populate the 'completeness' page

---

js/country.js
js/dataprovider.js
js/graphing.js
js/healthmap.js
rank/index.html

Add a sliding 7-day average window. Remove the need for centroids sent from the server.

---

js/dataprovider.js
js/healthmap.js

Update latest counts regularly in a running session

---

js/dataprovider.js
js/healthmap.js

Get data from the newer "aggregates" multi-day data source

---

country.html
css/styles.scss
js/dataprovider.js
js/diseasemap.js
js/graphing.js
js/healthmap.js
rank/index.html
scripts/deploy.py

Implementation of the "rank" page

---

completeness/index.html
js/completeness.js
js/diseasemap.js
js/healthmap.js
scripts/js_compilation.py

More splitting. Style changes for the 'completeness' page.

---

completeness/index.html
css/_media-queries.scss
css/_variables.scss
css/styles.scss
index.html
rank/index.html

Some styling simplifications and tweaks

---

completeness/index.html
css/_media-queries.scss
css/_variables.scss
css/styles.scss
index.html
js/completeness.js
js/dataprovider.js
js/healthmap.js
js/rank.js
rank/index.html

Add a top navigation bar to switch between the visualization views

---

css/_media-queries.scss
css/styles.scss
index.html
js/dataprovider.js
js/healthmap.js
scripts/data_util.py

Show total death count, some polishes

---

css/_variables.scss
css/styles.scss
js/diseasemap.js
js/healthmap.js

Museum of Science asked if we could provide a light theme, which would be more accessible to viewers with visual impairments. These changes add a hash for lighttheme, a light mapbox style, and styling for UI elements to match the light map.

Light theme

---

js/country.js
js/dataprovider.js
js/healthmap.js
js/rank.js
rank/index.html

Add color-coded continents for the 'rank' page

---

country.html
index.html
js/countrydashboard.js
js/diseasemap.js
js/healthmap.js
js/rank.js
js/sidebar.js
scripts/js_compilation.py

Split out more code from healthmap.js to separate files

---

css/styles.scss
index.html
js/casemapview.js
js/completenessview.js
js/dataprovider.js
js/diseasemap.js
js/main.js
js/rankview.js
js/syncview.js
js/timeanimation.js
js/view.js
rank/index.html

More object-oriented practices

---

css/_toggle.scss
css/_variables.scss
css/styles.scss
css/themed.scss
js/completenessview.js
js/diseasemap.js
js/graphing.js
js/historicalmapview.js
js/main.js
js/mapview.js
js/nav.js
js/rankview.js
js/syncview.js

'autodrive' fixes for the rank view, top nav style fixes

---

js/country.js
js/dataprovider.js
js/diseasemap.js
js/nav.js
js/view.js

A little documentation

---

css/styles.scss
js/rankview.js

Add a toggle for linear vs logarithmic scale in 'rank' view

---

config.json
deploy
js/diseasemap.js
js/main.js
js/sidebar.js
run
scripts/deploy.py

Replace the mapbox API token and data source URL on the fly as appropriate

---

README.md
run

Update documentation, ease local development a little more.

---

js/completenessmapview.js
js/freshnessmapview.js

Derive some more rgba colors from hex instead of hardcoding them again

---

index.html
js/percountrymapview.js
js/twodcoveragemapview.js
scripts/js_compilation.py

Extract some potentially common logic into a per-country map viiew

---

css/styles.scss
index.html
js/mapview.js
js/rankview.js
js/sidebar.js
js/syncview.js
js/view.js

Side bar and logo style changes

---

css/styles.scss
js/sidebar.js

Added a link and logo to G.h List at the bottom of the side bar

---

css/_variables.scss
css/styles.scss
css/themed.scss
index.html
js/aggregatemapview.js
js/casemapview.js
js/diseasemap.js
js/freshnessmapview.js
js/historicalmapview.js
js/main.js
js/mapview.js
js/percountrymapview.js
js/sidebar.js
js/twodcoveragemapview.js
scripts/js_compilation.py

Iterations with UX on visual appearance

---

scripts/data_util.py

Remove unused imports

---

js/casemapview.js

cc @rkassa cc @katelynnobrien 
See https://github.com/globaldothealth/list/issues/1055

Rename 'Cases' to 'Individual Cases'

---

css/styles.scss
js/sidebar.js

cc @katelynnobrien cc @rkassa
See https://github.com/globaldothealth/list/issues/1056

Do not show the 'per capita' checkbox by default

---

css/_variables.scss
css/styles.scss
js/sidebar.js

cc @rkassa cc @katelynnobrien 
See https://github.com/globaldothealth/list/issues/1056

Replace the colored circles representing cases per country with a progress-bar-looking UI

---

css/styles.scss

cc @katelynnobrien cc @rkassa
See https://github.com/globaldothealth/list/issues/1056

Style the side bar header to be closer to the mocks

---

css/styles.scss
scripts/deploy.py

Fix the download process for the Closure compiler

---

css/_variables.scss
css/styles.scss
css/themed.scss
deploy

- Update font to "Inter" with Arial, Helvetica, sans-serif fallbacks
- Update topbar to preferred layout per [this slide](https://docs.google.com/presentation/d/1YExjOd8qDXQ-yZm0LDJJXw3doI_V9cQGtPnHipX9FiU/edit?pli=1#slide=id.g987c4c1b8f_3_50)

Font & TopBar Changes

---

js/aggregatemapview.js
js/casemapview.js
js/dataprovider.js
js/dataprovider_test.js
tests/js_test.py

cc @katelynnobrien  cc @rkassa

Some style tweaks and bug fixes for map pop-ups

---

index.html

Fix absolute path for a couple of JS files

---

css/_variables.scss
css/styles.scss
css/themed.scss
js/historicalmapview.js
js/main.js
js/nav.js
js/sidebar.js

cc @rkassa cc @katelynnobrien 
Related to https://github.com/globaldothealth/list/issues/1084 and https://github.com/globaldothealth/list/issues/1079

Implement a "more" overflow menu for nav items, and (re-)implement a search field for the side bar

---

scripts/requirements.txt
scripts/update_covid19.py

This function generates three json files:
1. case counts by country, including JHU totals for measuring completeness
2. case counts by region (admin3)
3. count of total line list cases
json files are uploaded to S3 with copies for archival purposes.

add function for generation json of case counts from line list

---

css/styles.scss
css/themed.scss
deploy
js/aggregatemapview.js
js/casemapview.js
js/main.js
js/nav.js
js/twodcoveragemapview.js

- Link map popups to filtered country line list data
- Link map popup to filtered regional line list data
- "Country View" is default view on load

Additional UI changes to Map

---

config.json
js/aggregatemapview.js
js/casemapview.js
js/countrydashboard.js
js/dataprovider.js
js/sidebar.js
js/twodcoveragemapview.js

This only reworks the "country" and "coverage" maps to use the new aggregates in the S3 bucket.
@todo: REGIONAL map update (this will be in a separate PR, @calremmel )

Use json aggregates in S3 for COUNTRY and COVERAGE maps

---

js/main.js

now the cursor can be unpinned after clicking on a link.
https://github.com/globaldothealth/list/issues/1701

fixed unpinnable cursor

---

js/casemapview.js
js/dataprovider.js
js/diseasemap.js
js/mapview.js
js/nav.js
js/sidebar.js

This PR resolves the following issues:
- https://github.com/globaldothealth/list/issues/1786 
- https://github.com/globaldothealth/list/issues/1788
- https://github.com/globaldothealth/list/issues/1810
Also:
- console.log cleanup
- unmerged previous work around regional map circle markers

Fix filter link for regional data filters on popup

---

README.md
deploy
scripts/js_compilation.py

Put the info needed to run the build in one place, fix the shebang line on the build script so it actually runs, and fix the build so it works.

Document deployment

---

js/casemapview.js
js/mapview.js

**Changes**
- Fixed latitude and longitude mismatch in regional view, popups now appear in proper place

2201 - issues with dots in regional view
